name: elementable
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip

    # Testing
  - hypothesis
  - pytest
  - pytest-xdist
  - pytest-cov
  - codecov
  - numpy

  # optional
  - openmm
  - openff-units
  - unyt
  - pydantic


