name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
  
  # docs
  - ipython
  # - jupyter
  # - nbsphinx
  - sphinx > 2.0

  # optional
  - openmm
  - openff-units
  - unyt
  - pydantic

  - pip:
      - sphinx_rtd_theme
      - sphinxcontrib-bibtex
      - sphinx-sitemap